---
- name: Install git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Get updated python/ansible version
  apt_repository:
    repo: "{{ item }}"
  loop: ['ppa:ansible/ansible', 'ppa:deadsnakes/ppa']

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Upgrade ansible/python version
  apt:
    name: "{{ item }}"
  loop: ['software-properties-common', 'ansible', 'python3', 'python-psycopg2']

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family|lower }}.yml"

- name: Install AWX dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ awx_package_dependencies }}"

- name: Clone AWX into configured directory.
  git:
    repo: "{{ awx_repo }}"
    dest: "{{ awx_repo_dir }}"
    version: "{{ awx_version }}"
    update: "{{ awx_keep_updated }}"
    force: true
    accept_hostkey: true

- include: awx_install.yml
  when: awx_run_install_playbook